services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: games
      POSTGRES_PASSWORD: password_game
      POSTGRES_DB: games_data_and_score
    ports:
      - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admingame@example.com
      PGADMIN_DEFAULT_PASSWORD: adming
    ports:
     - "8080:80"
    depends_on:
     - postgres

volumes:
  postgres_data: